### ISSUE TITLE
Create proper fork of react-scripts

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/create-react-app#1]
Follow instructions at https://github.com/dvkndn/create-react-app/blob/c27cd91881fab5d71c554c1789ad7b24573509cd/packages/react-scripts/template/README.md#forking-as-alternative-to-ejecting to create a proper fork.

Use `@nlesc` as scope.

**Comment by sverhoeven** [comment]
As our `react-scripts` is not yet published on npmjs use local clone of this repo to test.

Use sinopia by starting it 

```
npm install sinopia2
node_modules/.bin/sinopia
# CTRL-C
vi ~/.config/sinopia/config.yaml
# Add `proxy: npmjs` to '@*/*' section
node_modules/.bin/sinopia
```

Make use of local registry by

```
npm set registry http://localhost:4873
npm adduser --registry http://localhost:4873
cd create-react-app/packages/react-scripts
npm publish
cd <some where>
create-react-app my-app --scripts-version @nlesc/react-scripts
```

**Comment by jspaaks** [comment]
```
npm get registry
https://registry.npmjs.org/
```

**Comment by sverhoeven** [comment]
Docker Sinopia does not proxy scoped packages like `@types/react`.
Fix by using sinopia2 and altered config:

```
npm install sinopia2
node_modules/.bin/sinopia
CTRL-C
vi ~/.config/sinopia/config.yaml
```
Add `proxy: npmjs` to `'@*/*'` section.
And start sinopia again.
