### ISSUE TITLE
code coverage should go back to original ts code

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/create-react-app#17]
see also #15, #6

**Comment by jspaaks** [comment]
stacktraces should also give pointers to original code

**Comment by sverhoeven** [comment]
Tested with class with 2 functions and testing one of them. Sadly reported coverage is incorrect.

**Comment by sverhoeven** [comment]
See if https://github.com/kulshekhar/ts-jest works. 
Seems it doesn't transpile ts>babel, but only ts, which might also work.

**Comment by sverhoeven** [comment]
The coverage can be generated with

```
CI=1 npm test -- --coverage --no-cache
```

The coverage can be found at `coverage/remapped/html/index.html`.

Not sure if transpile pipeline ts>babel>js gets correct coverage.
My tests in https://github.com/3D-e-Chem/molviewer-tsx report the correct coverage.
