### ISSUE TITLE
Transpile Typescript source code

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/create-react-app#2]
Add `ts` loader to webpack config for *.ts and *.tsx files.

See https://github.com/vgmr/create-ts-app for example.

**Comment by sverhoeven** [comment]
Another example https://github.com/mattiamanzati/create-react-app/tree/typescript-support

**Comment by sverhoeven** [comment]
And another https://www.npmjs.com/package/react-ts-scripts, needs to be npm installed to get to code as repo is 404.

**Comment by jspaaks** [comment]
preferred setup is to write ts, transpile to es6, then use the existing setup that facebook uses (transpiling es6 to es5 using babel)

**Comment by sverhoeven** [comment]
Sub features:
- [x] transpile from TS to JS
- [x] transpile TSX to JS
- [x] targets es5
- [x] targets latest chrome
- [x] targets latest firefox
- [x] targets latest edge
- [x] can handle TS2 @types/

**Comment by sverhoeven** [comment]
Tested example app on Chrome, Firefox, Edge and IE11.
