### ISSUE TITLE
add tslint config and command

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/create-react-app#20]
- force during pre build, errors should be terminal
- should work with tsx, e.g. with https://www.npmjs.com/package/tslint-react
- mirror eslint rules in tslint config see https://www.npmjs.com/package/tslint#custom-rule-sets-from-the-community

**Comment by sverhoeven** [comment]
Took tslint.json from molviewer and adjusted rules to so example code passes.

**Comment by sverhoeven** [comment]
Atm tslint shows warnings during `npm start`, but does not terminate. `npm run build` does not show warnings and does not terminate.

**Comment by jspaaks** [comment]
- add microsoft tslint rules 
- add 

```
https://github.com/Microsoft/tslint-microsoft-contrib
"react-no-dangerous-html": true,
"react-this-binding-issue": true,
"react-unused-props-and-state": true,
"react-anchor-blank-noopener": true,
"react-tsx-curly-spacing": [true, "never", {"allowMultiline": false}]]

https://github.com/palantir/tslint-react
"jsx-alignment": true,
"jsx-curly-spacing": already covered by tslint-microsoft-contrib/react-tsx-curly-spacing
"jsx-no-lambda": true,
"jsx-no-multiline-js: already covered by tslint-microsoft-contrib/react-tsx-curly-spacing
"jsx-no-string-ref": true,
"jsx-self-close": true
```
