### ISSUE TITLE
Enable tslint rules that require typecheck

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/create-react-app#23]
The following rules have been disabled:
*  "no-for-in-array": false,
* "restrict-plus-operands": false,

As these require type-check and type-check has not been enabled for tslint.

We would like to enable these rules.

**Comment by Maartenvm** [comment]
Is not fixed unfortunately. 
"npm start"  gives errors about rules that require type checking

**Comment by sverhoeven** [comment]
The webpack-tslint package does want work with typeCheck: true . 
Also the plugin `linter-tslint` in Atom and `tslint` in VSCode dont implement type check.

So will disable the rules again and disable the typecheck in npm run lint.

**Comment by sverhoeven** [comment]
Published packages
Changes:
- @nlesc/react-scripts: 0.1.0 => 0.1.1
- @nlesc/tslint-config-react-app: 1.1.0 => 1.1.1
