### ISSUE TITLE
Create project _here_ not in subdirectory

### ISSUE THREAD

**Issue by Maartenvm** [NLeSC/create-react-app#36]
Personally, I like to start my projects on Github, not locally. I setup Github repo and clone that and *then* start with a create-react-app command in that subdirectory.

This workflow currently makes a subdirectory in the one I just created named <project-name>.

If that's even ever desired behavior, can't we make the subdirectory optional at least?

**Comment by sverhoeven** [comment]
Already implemented by upstream repo, use `.` for example

```
create-react-app . --scripts-version @nlesc/react-scripts
```

To create app in current directory.
