### ISSUE TITLE
The travis build script fails

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/create-react-app#45]
It runs `tasks/e2e.sh` script which when run locally fails.

**Comment by sverhoeven** [comment]
``````
Tried to fix tasks/e2e.sh script in `travis-e2e` branch.

Fails with:
```
> node packages/react-scripts/scripts/build.js

Creating an optimized production build...
Error in bail mode: [default] /tmp/gg/packages/react-scripts/node_modules/@nlesc/tslint-config-react-app/node_modules/tslint/custom-typings/resolve.d.ts:28:2
Duplicate identifier 'export='.
```
``````

**Comment by sverhoeven** [comment]
Disabled Travis-CI build for now, will enable when this issue is fixed.

**Comment by bryantee** [comment]
Is this a bug? My builds were passing on Travis up until a certain commit. Now getting very generic error when building on Travis. Build goes fine locally.

```
Creating an optimized production build...
Failed to compile.
```

**Comment by sverhoeven** [comment]
For PR #47 I enabled Travis-CI again. 

Looking at https://travis-ci.org/NLeSC/create-react-app/builds/191663062
* The Node v6 builds have problems with a tslint rule, this could be corrected by #48.
* The Node v4 builds are missing Babel somehow

The method used at  https://github.com/NLeSC/create-react-app/blob/master/tasks/e2e.sh#L138 to use the react-scripts package seems to have problems with the scoped package name (<code>@nlesc/...</code>).  Switching to the method described at https://github.com/NLeSC/create-react-app/blob/master/development-setup.md to install the <code>@nlesc/react-scripts</code> package could be a work around.

**Comment by sverhoeven** [comment]
@bryantee what is the nodejs version you are using locally?

**Comment by bryantee** [comment]
@sverhoeven v6.9.2
