### ISSUE TITLE
Overwrite react-tsx-curly-spacing to never

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/create-react-app#46]
New version https://github.com/Microsoft/tslint-microsoft-contrib changed default to "always".

Offical React code and eslint use "never". So should we.

**Comment by mkuzak** [comment]
Here is nice explanation of what this option actually means.
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-spacing.md
